### ISSUE TITLE
Feature Request: Be able to specify location of output

### ISSUE THREAD

**Issue by digitalpenguin** [Sterc/modx-minify#21]
For example it would be nice not to have the minified file shown as being in /assets/components/modxminify/...

**Comment by jcdm** [comment]
+1 vote for this

**Comment by jcdm** [comment]
+1 for this feature

**Comment by ysanmiguel** [comment]
YES
and the option to use a MediaSource to upload the CSS/JS to AmazonS3

**Comment by joeke** [comment]
System settings for cache_path and cache_url are added in the 1.0.1 release: https://modx.com/extras/package/modxminify
Thanks for your PR @digitalpenguin !
