### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Kvodnon** [Sterc/modx-minify#22]
MODX 2.7.1-pl
I'm trying to add a new group, but after clicking nothing happens.
Netwrok response:
`{"success":false,"message":"","total":1,"data":[{"id":"name","msg":"Key is not specified."}],"object":[]}`

**Comment by pepebe** [comment]
Same here. MODX 2.6.0, latest Version (1.0.0pl)

**Comment by gpsietzema** [comment]
@Kvodnon @pepebe I'm having difficulties reproducing it. Can you tell me a little more?
- Which browser are you using
- Quick list of other extras would be nice :)

**Comment by pepebe** [comment]
@gpsietzema Hi, sorry for being late to the party. I'll look into this some more and give feedback.

**Comment by pepebe** [comment]
Ok, I had another look at the problem and it seems to be a bit different. I even don't see the network response anymore. Reinstalled the whole package, but without any improvements on the situation. 

I'll open a new issue.

**Comment by messyp** [comment]
Any update, just installed and not working for me

**Comment by joeke** [comment]
We just released the 1.0.1 version: https://modx.com/extras/package/modxminify
Can you check if you still have the issue?

**Comment by Kvodnon** [comment]
Problem solved, thanks.

**Comment by inreti-sb** [comment]
Please close this issue. Thanks!
