### ISSUE TITLE
CMP doesn't work

### ISSUE THREAD

**Issue by pepebe** [Sterc/modx-minify#25]
This is how my network response looks on a server where modx-minify works (MODX 2.6.1):

![bildschirmfoto vom 2018-01-09 11-26-41](https://user-images.githubusercontent.com/667315/34716393-006c96b6-f530-11e7-94ea-8dff5f4bfedc.png)

The dev tools show all the files requested after loading the minify manager page. I can add groups and files without any problem.

This is how it look on another modx setup (2.6.0).

![bildschirmfoto vom 2018-01-09 11-29-56](https://user-images.githubusercontent.com/667315/34716542-7028d1b8-f530-11e7-964e-056a464ee08f.png)

No files are loaded, I can't add groups or files.

Both installations are on the same server. I've reinstalled modx-minifyx two times (no effect). 

At the moment I can'*t update the system to 2.6.1, so I can't check if the modx Version is the root of the problem.

I don't see any error on my server or any js errors on the console.

Any idea, whats going on?

Update:

I've reset all file and folder permissions (644/755) in 

core/components/modx-minify 
and assets/components/modx-minify

Afterwards the CMP loaded the necessary files, but I still couldn't add groups or files to the CMP.

**Comment by pepebe** [comment]
Now I also get a connector error:
```
{success: false, message: "object_err_save", total: 0, data: [], object: []}
data:[]
message:"object_err_save"
object:[]
success:false
total:0
```

**Comment by pepebe** [comment]
Installed Extras:

![bildschirmfoto vom 2018-01-09 11-58-46](https://user-images.githubusercontent.com/667315/34717795-8fb748ee-f534-11e7-8c9f-5365b5622ca2.png)
![bildschirmfoto vom 2018-01-09 11-58-28](https://user-images.githubusercontent.com/667315/34717796-8fd10194-f534-11e7-84a5-a0d8da91cde0.png)
![bildschirmfoto vom 2018-01-09 11-58-14](https://user-images.githubusercontent.com/667315/34717797-8feb73bc-f534-11e7-91b2-3fbca101101a.png)

Happens in Google Chrome and Firefox (latest versions)

**Comment by pepebe** [comment]
This issues was solved by renaming the modxminify tables to use the table prefix (in my case modxij_ instead of modx_).

**Comment by joeke** [comment]
@pepebe Yes when the table_prefix is not the default `modx_` will not work. Will be fixed in the next version.

**Comment by joeke** [comment]
Version 1.0.1 is released! https://modx.com/extras/package/modxminify
