### ISSUE TITLE
Can't Create or Save Anything

### ISSUE THREAD

**Issue by MarkG33** [Sterc/modx-minify#26]
Just installed this and it doesn't work.
It installed ok but when I try to add a group it won;t do anything.

I hit save and nothing happens.

Is there some secret setting that I need to enable to make this work or is it just broken?

Please advise.

Thanks

**Comment by pepebe** [comment]
Hi,

this problem is already known, but the cause is still unknown.

Please share you MODX Version and some background information about your server environment (PHP version, Apache or Nginx).

**Comment by MarkG33** [comment]
Thanks,

Modx version Revo 2.5.8
msql  5.6.38
PHP  5.6.33
Apache

As I said it installs ok and I can open it in the manager under the Extras tab.
And while I can add info into the fields when I press Save nothing happens.

No errors, no crashes or freezes, just nothing.
And i can close the extra no problem.

There are no error messages in the log.

Hope that helps.

**Comment by pepebe** [comment]
Same on my side. Today after updating to 2.6.1 and deleting the cache, I found this one (not sure if it was there before):

```
Error 42S02 executing statement: Array ( [0] => 42S02 [1] => 1146 [2] => Table 'instance_c0259_modx.modxij_minify_groups' doesn't exist ) 
```

Turns out that the program setup ignores individual table prefixes... Have a look at your database. You should find two modx minify tables inside:

* prefix_minify_files
* prefix_minify_groups

"prefix_" should be identical to all the other prefixes used by your installation.

If you have these tables, but with a wrong prefix, just change the table name. If you don't have them, let me know.

**Comment by MarkG33** [comment]
What I ended up doing was just copy and pasting all css and js into two separate files, then minifying them via yslow.

It was a bit of work but it did the trick.

So I bypassed modx-minify altogether.

Probably better that way.

Thanks anyway.

**Comment by pepebe** [comment]
It would be great If you could confirm the prefix issue. If you habe the time and the means, please have a look at your database.

**Comment by MarkG33** [comment]
I've already uninstalled it.

However the tables are still in my database.
modx_minify_files
modx_minify_groups

another however is that none of my other tables has that modx_prefix.

So are you saying I should delete the modx_ prefix?

**Comment by pepebe** [comment]
I'm about 99% sure that the wrong prefixes are the root of the problem (though there might also be a permission problem on top of that). If you don't use minify, I don't see any proplem deleting both tables.

**Comment by MarkG33** [comment]
Thanks

for all your help.

You can mark this one closed for me.
