### ISSUE TITLE
Minify process is too zealous - breaks Bootstrap form styling

### ISSUE THREAD

**Issue by digitalpenguin** [Sterc/modx-minify#28]
Some CSS rules require spaces. For example Bootstrap has the following applied to its <select> input elements: 

`height: calc(2.25rem + 2px)`.

The + requires a space on either side or it doesn't work. Unfortunately the spaces get stripped out leaving the input oddly sized. 

I've worked around this on my current project by adding inline css to the form but it'd be great to get this fixed properly.

**Comment by inreti-sb** [comment]
Had the same issue using Bulma Framework.

**Comment by black-meridian** [comment]
I just update the folder /core/components/modxminify/assetic/vendor/leafo/

with the last version of scssphp https://github.com/leafo/scssphp and it's now working

**Comment by devlanda** [comment]
I will close this issue. Please see #41.
