### ISSUE TITLE
Assetic Twig conflict

### ISSUE THREAD

**Issue by sdrenth** [Sterc/modx-minify#32]
I'm using Commerce and Modxminify and the two conflict because both are loading different versions of Twig through composer, causing 500 errors because Commerce loads the Modx Minify version of Twig. In MODX Minify it is loaded through the Assetic composer file. 

Could you remove Twig from the Assetic composer file? I've tested without and everything still seems to work fine and it fixed my issue.

**Comment by joeke** [comment]
Should be fixed with the 1.0.1 release: https://modx.com/extras/package/modxminify
