### ISSUE TITLE
Some SCSS Errors with Leafo's ScssPhp can be fixed

### ISSUE THREAD

**Issue by mindeffects** [Sterc/modx-minify#35]
This thread saved my life when I had trouble compiling a standard Foundation SCSS:
https://github.com/leafo/scssphp/issues/446

This post (https://github.com/leafo/scssphp/issues/446#issuecomment-299485604) held the key for the solution, but it is not update save. 
Maybe you guys want to patch ModxMinfy a little or maybe not... 'sup to you.

Just in case someone gets strange errors from ModxMinify this here might help, so I wrote these lines. ;-)

**Comment by devlanda** [comment]
I will close this issue because as it is related #41.
