### ISSUE TITLE
Issue using calc()

### ISSUE THREAD

**Issue by kolbykruger** [Sterc/modx-minify#40]
I am having an issue where the minification of my stylesheet is removing the spacing in any/all calc() functions.

In the inspector, not having a space in your calc function breaks it.

Another thing to note is it only happens when the operator in the calc() function is a `+`.

I have temporarily fixed my calc functions by changing:
`font-size: calc(2.5rem + 1.5vw);` to `font-size: calc(2.5rem - -1.5vw);`

Anyone have a solve for this?

**Comment by devlanda** [comment]
I think this is related to #28. I will close this issue.
